### ISSUE TITLE
VisionReplayManager should provide a way to obtain the Route object used for the recorded nav session

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#221]
## Description
When using the DataRecorder app, the user creates a nav session to their chosen destination.

The contents of that nav session should be recorded and provided to the app that is playing back the Vision data using the replay manager. Adding a delegate method that sends the JSON response from the directions endpoint and any reroute events would probably be the best way, something like: 

    func visionManager(_ visionManager: VisionManagerProtocol, didUpdateRoute route: <String, Any>)

## Goal
The goal is for the replay delegate to have all the necessary info to replay what was recorded using the Mapbox navigation engine. We need the right JSON blob to supply to the initializer for MBRoute.Route. Right now you need to create a route response in advance for each recorded session and supply it to the nav SDK in order to have a Mapbox navigation session active.

**Comment by chezzdev** [comment]
Hey @avi-c, thanks for reporting the issue. 

We're currently working on providing a recorded route back to SDK user in the replay mode. The thing is we don't record all the info that's available from `MBRoute` since we don't need it for Vision and AR to work. You can check out the data that's available [here](https://docs.mapbox.com/ios/api/vision/ar-data-types/0.9.0/Classes/Route.html).

**Comment by chezzdev** [comment]
Route update is implemented in VisionAR 0.12.0. The only thing to keep in mind is that we return `MBVRoute`, the same structure user provides to `VisionARManager` in "record" mode. It's not a full response from Directions API and Vision doesn't store one.
